#!/usr/bin/env bash
# Dependency/toolchain installer for CPU llama.cpp Lab v5.
# Policy: use only the host distribution's configured repositories. Never add PPAs.
set -u
PKG="$(cd "$(dirname "$0")/.." && pwd)"
ROOT="${LAB_ROOT:-$(dirname "${HW_JSON:-$PWD/.cpu-llama-lab/hardware.json}")}"
HW="${HW_JSON:-$ROOT/hardware.json}"
LOG="$ROOT/logs/install-deps.log"
TOOLS="$ROOT/tools"
mkdir -p "$ROOT/logs" "$TOOLS/bin" "$ROOT/cache" "$ROOT/venvs"
exec > >(tee -a "$LOG") 2>&1

need_sudo(){ [ "$(id -u)" -eq 0 ] || printf '%s' sudo; }
SUDO="$(need_sudo)"
have(){ command -v "$1" >/dev/null 2>&1; }
run(){ printf '+ '; printf '%q ' "$@"; printf '\n'; "$@"; }
apt_has(){ apt-cache show "$1" >/dev/null 2>&1; }
dnf_has(){ dnf -q info "$1" >/dev/null 2>&1; }

write_env(){
  cat > "$ROOT/env.sh" <<EOFENV
# Generated by CPU llama.cpp Lab. Source is optional; cpu-llama-lab.sh does so automatically.
export CPU_LLAMA_LAB_TOOLS="$TOOLS"
export PATH="$TOOLS/bin:\${PATH}"
export XDG_CACHE_HOME="$ROOT/cache/xdg"
export UV_CACHE_DIR="$ROOT/cache/uv"
export UV_PYTHON_INSTALL_DIR="$ROOT/tools/uv-python"
export UV_TOOL_DIR="$ROOT/tools/uv-tools"
export UV_TOOL_BIN_DIR="$ROOT/tools/bin"
export CCACHE_DIR="$ROOT/cache/ccache"
export CCACHE_BASEDIR="$ROOT"
export CCACHE_COMPILERCHECK=content
EOFENV
}
write_env
# shellcheck disable=SC1090
. "$ROOT/env.sh"

install_apt(){
  base=(git cmake ninja-build ccache curl ca-certificates jq numactl libnuma-dev libopenblas-dev pkg-config python3 python3-dev python3-venv build-essential dmidecode binutils time util-linux hwloc file)
  run $SUDO apt-get update || return 1
  run $SUDO apt-get install -y "${base[@]}" || return 1

  # perf is tied to the running Ubuntu kernel. Prefer the exact kernel tools; then the distro meta-package.
  k="$(uname -r)"
  perf_installed=0
  for p in "linux-tools-$k" linux-tools-generic linux-tools-common; do
    if apt_has "$p"; then
      if run $SUDO apt-get install -y "$p"; then perf_installed=1; fi
    fi
  done
  [ "$perf_installed" -eq 1 ] || echo "WARN: no matching Ubuntu linux-tools package found for kernel $k; perf will be probed separately."
}

install_dnf(){
  base=(git cmake ninja-build ccache curl ca-certificates jq numactl numactl-devel openblas-devel pkgconf-pkg-config python3 python3-devel gcc gcc-c++ dmidecode binutils time util-linux hwloc file perf)
  run $SUDO dnf install -y "${base[@]}" || return 1
}

install_pacman(){
  run $SUDO pacman -Sy --needed --noconfirm git cmake ninja ccache curl ca-certificates jq numactl openblas pkgconf python gcc dmidecode binutils time util-linux hwloc file perf || return 1
}

if have apt-get; then install_apt || exit 1
elif have dnf; then install_dnf || exit 1
elif have pacman; then install_pacman || exit 1
else
  echo "Unsupported package manager. Install git cmake ninja ccache numactl OpenBLAS pkg-config Python binutils and a C/C++ compiler." >&2
  exit 2
fi

cls="$(python3 -c 'import json,sys;print(json.load(open(sys.argv[1]))["cpu"]["class"])' "$HW" 2>/dev/null || echo unknown)"

# KNL requires a compiler that still truly supports -march=knl. Probe both C and C++.
if [ "$cls" = knl ]; then
  ok=""
  for c in gcc-14 gcc-13 gcc-12 gcc-11 gcc-10 gcc; do
    have "$c" || continue
    cxx="${c/gcc/g++}"; have "$cxx" || continue
    cp="$ROOT/.knl-cc-probe.c"; cpp="$ROOT/.knl-cxx-probe.cpp"
    printf 'int x;\n' > "$cp"; printf '#include <cstdint>\nint main(){return 0;}\n' > "$cpp"
    if "$c" -march=knl -c "$cp" -o "$ROOT/.knl-cc-probe.o" >/dev/null 2>&1 && \
       "$cxx" -march=knl -c "$cpp" -o "$ROOT/.knl-cxx-probe.o" >/dev/null 2>&1; then
      ok="$c"; rm -f "$cp" "$cpp" "$ROOT/.knl-cc-probe.o" "$ROOT/.knl-cxx-probe.o"; break
    fi
    rm -f "$cp" "$cpp" "$ROOT/.knl-cc-probe.o" "$ROOT/.knl-cxx-probe.o"
  done

  if [ -z "$ok" ] && have apt-get; then
    for v in 14 13 12 11; do
      if apt_has "gcc-$v" && apt_has "g++-$v"; then
        echo "Installing distro GCC $v for KNL (-march=knl)..."
        if run $SUDO apt-get install -y "gcc-$v" "g++-$v"; then
          if printf 'int x;' | "gcc-$v" -x c -march=knl -c -o "$ROOT/.knl-cc-probe.o" - >/dev/null 2>&1; then
            ok="gcc-$v"; rm -f "$ROOT/.knl-cc-probe.o"; break
          fi
        fi
      fi
    done
  fi

  if [ -z "$ok" ]; then
    cat >&2 <<'EOFERR'
No distro-installed/package-manager GCC supports -march=knl.
GCC 15 removed KNL target support. Install GCC 14 or earlier, then rerun.
The suite intentionally will not add a third-party PPA or mix libraries from another distribution release.
EOFERR
    exit 3
  fi
  echo "KNL compiler selected: $ok ($($ok --version | head -1))"
  printf '%s\n' "$ok" > "$ROOT/knl-cc.txt"

  # memkind is optional and only useful for heterogeneous/HBM memory experiments.
  if have apt-get && apt_has libmemkind-dev; then
    run $SUDO apt-get install -y libmemkind-dev || echo "WARN: libmemkind-dev install failed; NUMA-based Flat-mode tests remain available."
  elif have dnf && dnf_has memkind-devel; then
    run $SUDO dnf install -y memkind-devel || echo "WARN: memkind-devel install failed; NUMA-based Flat-mode tests remain available."
  else
    echo "INFO: distro memkind development package not available; HBM/memkind-specific build ablations will be skipped."
  fi
fi

# Install uv privately beneath LAB_ROOT, pinned by default. Do not modify shell rc files or $HOME.
UV_VERSION="${UV_VERSION:-0.12.5}"
if [ ! -x "$TOOLS/bin/uv" ]; then
  if have uv && [ "${LAB_USE_SYSTEM_UV:-0}" = 1 ]; then
    echo "Using explicitly requested system uv: $(command -v uv)"
  elif have curl; then
    echo "Installing private uv $UV_VERSION under $TOOLS/bin ..."
    curl -LsSf "https://astral.sh/uv/$UV_VERSION/install.sh" | env UV_UNMANAGED_INSTALL="$TOOLS/bin" UV_NO_MODIFY_PATH=1 sh || echo "WARN: private uv installation failed; EvalPlus quality tests will be skipped unless uv is provided."
  fi
fi

# Distribution package-manager consistency checks. These do not replace the post-build ABI audit.
if have apt-get; then
  run $SUDO apt-get check || { echo "ERROR: apt dependency consistency check failed."; exit 4; }
  audit="$(dpkg --audit 2>&1 || true)"
  if [ -n "$audit" ]; then
    echo "WARN: dpkg --audit reported issues:"
    printf '%s\n' "$audit"
    [ "${LAB_STRICT_INSTALL:-0}" = 1 ] && exit 5
  fi
  apt-mark showhold > "$ROOT/apt-held-packages.txt" 2>/dev/null || true
fi

# perf usability check: executable presence alone is not enough.
PERF_STATUS=missing
if have perf; then
  if perf version >/dev/null 2>&1; then
    if perf stat -e cycles,instructions -- true >/dev/null 2>"$ROOT/logs/perf-probe.stderr"; then PERF_STATUS=ok
    elif grep -Eqi 'permission|perf_event_paranoid|not supported|No permission' "$ROOT/logs/perf-probe.stderr"; then PERF_STATUS=permission-or-policy
    else PERF_STATUS=installed-but-unusable
    fi
  fi
fi
printf '%s\n' "$PERF_STATUS" > "$ROOT/perf-status.txt"
echo "perf_status=$PERF_STATUS"

write_env
echo "Dependencies ready. Local tool environment: $ROOT/env.sh"
